import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  metadataBase: new URL("https://noblu.pl"),
  title: "Noblu Beauty Room Kraków | Manicure, paznokcie i beauty premium",
  description:
    "Noblu Beauty Room to salon beauty premium w Krakowie przy ul. Orzechowej 4/lok.1. Manicure, stylizacja paznokci, rzęsy i rezerwacja online przez Booksy.",
  keywords: [
    "Noblu Beauty Room",
    "manicure Kraków",
    "paznokcie Kraków",
    "salon beauty Kraków",
    "stylizacja paznokci Kraków",
    "beauty room Kraków",
    "manicure Kraków",
"pedicure Kraków",
"stylizacja rzęs Kraków",
"salon beauty Kraków",
"beauty room Kraków",
"paznokcie hybrydowe Kraków",
"manicure hybrydowy Kraków",
"salon paznokci Kraków",
"beauty premium Kraków",
"stylizacja rzęs Kraków",
"rzęsy Kraków",
"przedłużanie rzęs Kraków",
"lash artist Kraków",
"rzęsy premium Kraków",
"lifting rzęs Kraków",
"beauty studio Kraków",
"naturalne rzęsy Kraków",
"objętościowe rzęsy Kraków",
"salon rzęs Kraków",
"rzęsy 1:1 Kraków",
"rzęsy volume Kraków",
"stylizacja oka Kraków",
"luksusowy salon beauty Kraków",
"beauty premium Kraków",
"najlepszy manicure Kraków Podgórze",
"paznokcie hybrydowe Kraków Orzechowa",
"pedicure SPA Kraków",
"stylizacja rzęs Kraków Podgórze",
"salon paznokci z dobrymi opiniami Kraków",
"gdzie zrobić paznokcie żelowe w Krakowie",
"Noblu Beauty Room opinie, cennik, adres",
"premium manicure Kraków",
"luxury beauty Kraków",
"estetyczny manicure Kraków",
"minimalistyczne paznokcie Kraków",
"naturalne paznokcie Kraków",
"clean girl nails Kraków",
"quiet luxury beauty Kraków",
"elegancki salon beauty Kraków",
"kameralny salon beauty Kraków",
"salon beauty premium Kraków",
"exclusive beauty room Kraków",
"nowoczesny salon beauty Kraków",
"beauty experience Kraków",
"instagram beauty salon Kraków",
"luksusowy manicure Kraków",
"manicure premium Kraków",
"premium nails Kraków",
"beauty aesthetic Kraków",
"modne paznokcie Kraków",
"trendy nails Kraków",
"salon instagramowy Kraków",
"najlepszy manicure Kraków",
"top beauty salon Kraków",
"nude nails Kraków",
"natural lash look Kraków",
"premium lashes Kraków",
"beauty lounge Kraków",
"relaks beauty Kraków",
"kobiece beauty studio Kraków",
"spa manicure Kraków",
"manicure Podgórze",
"manicure Podgórze Duchackie",
"manicure Łagiewniki",
"manicure Borek Fałęcki",
"manicure Ruczaj",
"manicure Kurdwanów",
"paznokcie Podgórze",
"paznokcie Łagiewniki",
"paznokcie Borek Fałęcki",
"paznokcie Ruczaj",
"paznokcie Kurdwanów",
"manicure południe Krakowa",
"rzęsy Podgórze",
"stylizacja rzęs Łagiewniki",
"rzęsy Ruczaj",
"przedłużanie rzęs Kurdwanów",
"rzęsy Borek Fałęcki",
"salon beauty Podgórze",
"beauty room Łagiewniki",
"premium beauty Ruczaj",
"salon beauty Borek Fałęcki",
"beauty studio Kurdwanów",
"premium manicure Podgórze",
"luksusowy salon beauty Podgórze",
"kameralny salon beauty Kraków południe",
"premium nails Łagiewniki",
"beauty premium Ruczaj",
"quiet luxury beauty Kraków południe",
"rzęsy Podgórze",
"rzęsy Podgórze Duchackie",
"rzęsy Łagiewniki",
"rzęsy Borek Fałęcki",
"rzęsy Ruczaj",
"rzęsy Kurdwanów",
"stylizacja rzęs Podgórze",
"stylizacja rzęs Łagiewniki",
"stylizacja rzęs Ruczaj",
"stylizacja rzęs Borek Fałęcki",
"stylizacja rzęs Kurdwanów",
"przedłużanie rzęs Podgórze",
"przedłużanie rzęs Łagiewniki",
"przedłużanie rzęs Ruczaj",
"przedłużanie rzęs Borek Fałęcki",
"przedłużanie rzęs Kurdwanów",
"rzęsy premium Kraków południe",
"premium lashes Podgórze",
"naturalne rzęsy Podgórze",
"rzęsy 1:1 Podgórze",
"rzęsy volume Podgórze",
"lash artist Podgórze",
"salon rzęs Łagiewniki",
"salon rzęs Ruczaj",
"salon rzęs Borek Fałęcki",
"salon rzęs Kurdwanów",
"beauty lashes Kraków południe",
"luksusowe rzęsy Kraków",
"kameralny salon rzęs Kraków",
"natural lash look Kraków",
"premium lash studio Kraków",
"lifting rzęs Podgórze",
"lifting rzęs Łagiewniki",
"lifting rzęs Ruczaj",
"lifting rzęs Borek Fałęcki",
"lifting rzęs Kurdwanów",


  ],
  openGraph: {
    title: "Noblu Beauty Room Kraków",
    description:
      "Salon beauty premium w Krakowie. Zarezerwuj wizytę online przez Booksy.",
    url: "https://noblu.pl",
    siteName: "Noblu Beauty Room",
     images: [
    {
      url: "https://noblu.pl/logo.png",
      width: 1200,
      height: 630,
      alt: "Noblu Beauty Room Kraków",
    },
  ],
    locale: "pl_PL",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
